global:
  scrape_interval: 5s
  scrape_timeout: 5s
  evaluation_interval: 30s

scrape_configs:
- job_name: 'budget-tracker-webapi'
  honor_labels: true
  honor_timestamps: true
  scrape_interval: 5s
  scrape_timeout: 5s
  metrics_path: /metrics
  scheme: https
  follow_redirects: true
  static_configs:
    - targets: ['host.docker.internal:5001']
  tls_config:
    insecure_skip_verify: true